language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
install:
  - pip install -r requirements-test.txt
  - pip install coveralls

script:
  - coverage run --source=berserker_resolver setup.py test
after_success:
  - coveralls
