language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then travis_retry pip install dnspython3; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install dnspython; fi
script:
  - coverage run --source=berserker_resolver setup.py test
after_success:
  - coveralls
